# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0010_auto_20170120_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nickname',
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Username'),
        ),
    ]
